### ISSUE TITLE
Python lower than 3.6 not supported

### ISSUE THREAD

**Issue by Igoranze** [jberghoef/wagtail-tag-manager#56]
**Describe the bug**
When using python 3.5 or lower the following code is "invalid syntax"

```
return int(random.random() * 2_147_483_647)
                                         ^
SyntaxError: invalid syntax
```

The code can be found in "wagtail_tag_manager/config.py", line 140"

The underscore in numerical literals is not supported in lower versions of python: https://www.python.org/dev/peps/pep-0515/

**To Reproduce**
1. Install everything with python3.5
2. run migrations

**Expected behavior**
Migration file is created, but this does not happen because the code fails.

**Desktop (please complete the following information):**
 - Debian 9
 - Python 3.5
 - Wagtail 2.5.1 / Django 2.2.3

**Comment by jberghoef** [comment]
Thank you for your contribution! I've merged your pull request.
