### ISSUE TITLE
Wagtail Tag Manager breaks sitemap generator

### ISSUE THREAD

**Issue by ZuSe** [jberghoef/wagtail-tag-manager#61]
**Describe the bug**
WTM seems to break the generation of the sitemap.xml.

```
Traceback (most recent call last):
  File "venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "venv/lib/python3.7/site-packages/wagtail_tag_manager/middleware.py", line 31, in __call__
    self._add_instant_tags()
  File "venv/lib/python3.7/site-packages/wagtail_tag_manager/middleware.py", line 55, in _add_instant_tags
    body.append(element)
AttributeError: 'NoneType' object has no attribute 'append'
```

**To Reproduce**
Install WTM with middleware enabled according to docs

Load sitemap in your urls
path('^sitemap\.xml$', sitemap),

`from wagtail.contrib.sitemaps.views import sitemap`

add it to urls

**Expected behavior**
Sitemap.xml should be generated

**Screenshots**
No need, see above

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: All
 - Version: wagtail-tag-manager==0.20.1, wagtail==2.6.2

**Additional context**

**Comment by jberghoef** [comment]
Fixed in #62

**Comment by ZuSe** [comment]
Do you mind releasing a new version with the fix?

**Comment by jberghoef** [comment]
Done, should be available shortly.
