### ISSUE TITLE
Accept all button cookie_bar

### ISSUE THREAD

**Issue by D0N2k** [jberghoef/wagtail-tag-manager#75]
Hey,
is it possible to add an accept all button to the cookie_bar and deselect "Preferences" and "Statistics" by default?

**Comment by jberghoef** [comment]
Hi D0N2k,

Thank you for your question. This is not functionality added by default, but you could build this yourself with some JavaScript and by overwriting the Cookiebar template file.
https://github.com/jberghoef/wagtail-tag-manager/blob/master/src/wagtail_tag_manager/templates/wagtail_tag_manager/templatetags/cookie_bar.html

Hope this helps!
