### ISSUE TITLE
Tag manager installation downgrades wagtail

### ISSUE THREAD

**Issue by RadioErewan** [jberghoef/wagtail-tag-manager#84]
Collecting wagtail<2.12,>=2.1
  Using cached wagtail-2.11.6-py3-none-any.whl (11.0 MB)

Installing collected packages: wagtail
  Attempting uninstall: wagtail
    Found existing installation: wagtail 2.12.3
    Uninstalling wagtail-2.12.3:
      Successfully uninstalled wagtail-2.12.3
Successfully installed wagtail-2.11.6

**Comment by jberghoef** [comment]
Hi @RadioErewan, I'm having some trouble reproducing this. What version of Wagtail Tag Manager are you using?

**Comment by RadioErewan** [comment]
```
python -m pip freeze
...
wagtail==2.12.3
wagtail-cache==1.0.2
wagtail-extras==0.2.8
wagtail-tag-manager==0.25.0
```
(wagtail upgraded after downgrade)

**Comment by jberghoef** [comment]
The interessting thing is that is seems to pin wagtail to the correct version with `wagtail==2.12.3`. Are you certain this is not caused by a different package?

**Comment by jberghoef** [comment]
@RadioErewan I've actually found the issue, and released a new version. Could you validate if everything is working as intended by using `wagtail-tag-manager==0.25.1`?

**Comment by RadioErewan** [comment]
```
Installing collected packages: wagtail-tag-manager
  Attempting uninstall: wagtail-tag-manager
    Found existing installation: wagtail-tag-manager 0.25.0
    Uninstalling wagtail-tag-manager-0.25.0:
      Successfully uninstalled wagtail-tag-manager-0.25.0
Successfully installed wagtail-tag-manager-0.25.1
```
Thank you

**Comment by jberghoef** [comment]
You’re very welcome
